# Hello, and welcome to my settings ripped straight from the 'fusion' branch.
# nyah, you liek kissing bois don't you >:3

Settings:
    eventTime: 5
    maxRandomTime: 15
    skipStartup: 0
    debugMode: 0
    defLang: "en-us"
    localization: ("en-us", "pt-br")
    masterVol: 100

Music:
    filename: vibing_over_venus.mp3
    loopCount: -1

Customization:
# THIS TIME THIS WILL FUCKING WORK WHEN I WORK ON UI (08/10/2025)
    wallpaperType: solid
    titleBarColor: d1c1f4
    backgroundColor: 9485b5
    textColor: FFFFFF
    SecondColor: 560080
    elementColor: 9485b5